### ISSUE TITLE
Allow to run without old com.mongodb classes

### ISSUE THREAD

**Issue by velias** [ozwolf-software/mongo-trek#13]
Hi, I have problem to run migrations in Quarkus tests due to `java.lang.ClassNotFoundException: com.mongodb.Mongo`. Looks like all classes directly from `com.mongodb` package are not there due to some newer mongo driver used. And even I use `public MongoTrek(String migrationsFile, MongoDatabase database)` constructor it fails (interesting it fails only in tests, but works in normal start, some classloading magic probably). 

I think solution should be to create something like `MongoTrekNew`  which works only with `MongoDatabase` and performs migration. Then MongoTrek could keep the `com.mongodb` stuff to create `MongoDatabase` from url and then delegate all calls to new implementation. So it will be fully backward compatible, but users in newer frameworks with newer drivers only can use `MongoTrekNew` to prevent ClassNotFound exceptions.
WDYT?

**Comment by OzWolf** [comment]
Hmm...the latest version of the library was built and tested against the `3.12.5` version of the Mongo Java Driver (released on 2nd June 2020).

This scenario would be occurring because the Mongo Java Driver is not available to the class loader that is loading the mongoTrek library.  Because this library stipulates the mongo-java-driver as a provided dependency to allow developers to use a version aligned with their ecosystem, that driver library needs to be available for mongoTrek to access.

**Comment by velias** [comment]
Quarkus looks to use `mongodb-driver-sync` and `mongodb-driver-reactivestreams` respectively, both 4.0.3 currently. They both use `mongodb-driver-core` 4.0.3. I'm not sure how they exactly relate to Mongo Java Driver you mention. Isn't it the one marked as legacy at http://mongodb.github.io/mongo-java-driver/4.0/driver/getting-started/installation/ ?. As I wrote, part of mongo-trek which uses `MongoDatabase` only works well with them (I created stripped version of `MongoTrek` to test it), only problem is with this part which creates mongo connection from url. If it will be derived to separate class then I believe mongo-trek should work correctly even for these new drivers.

**Comment by OzWolf** [comment]
Ah, right...that clears it up.  The `mongo-java-driver` library hasn't been deprecated _yet_.  It was the original and still heavily used MongoDB driver library for JVM.  Even the `mongodb-driver-sync` entry on Maven Central points back at the the mongo/mongo-java-driver here on GitHub.

I've been meaning to figure out a strategy for supporting both because the `org.mongodb:mongo-java-driver` library hasn't been deprecated yet (most likely due to it's proliferation for years).

I generally don't like supporting conflicting code dependencies in the same library because you can end up with unexpected behaviour.

I'll most likely branch or fork this library to support both variations of the Mongo library.

**Comment by velias** [comment]
Looks like exact problem is with `com.mongodb.Mongo` class, it is not present even in mongodb-driver-legacy
It is used only in 
```
 @SuppressWarnings("deprecation")
    private DB connectTo(final MongoClientURI uri) {
        Mongo mongo = new MongoClient(uri);
        return mongo.getDB(uri.getDatabase());
    }
```
so maybe even small change of one line to `MongoClient mongo = new MongoClient(uri);` and remove of the import f unused class should help to obey this problem.

**Comment by velias** [comment]
Just tested in my code, and this small change (and inclusion of the mongodb-driver-legacy ) really helped.

**Comment by OzWolf** [comment]
I'm not a fan of taking the quick solution here.  Placing the dependency on the `mongo-driver-legacy` library to ensure internal workings is contrary to my design choices and requires everyone using the newest drivers to keep having to drag around the legacy driver just for the sake of getting _this_ library running.

I will upgrade the library to version `5.0.0` which will move to supporting the sync driver while `4.x` will become the terminating major version for the legacy driver.

**Comment by velias** [comment]
OK, sure, I respect your decision.
If you would be willing to change this one line (the change is fully backward compatible with current version) then it will be much appreciated, otherwise I'll wait for version 5.0 of this great tool. Thanks a lot in advance.

**Comment by OzWolf** [comment]
I have upgraded the library.  Assuming it passes muster through the Sonatype verification process (and I haven't missed a signature file) it _should_ be in Maven central in a few hours.

Otherwise it'll be there in the next 12 when it's daylight here again.

**Comment by OzWolf** [comment]
5.0.0 of the library is now available in Maven Central with support for the `mongo-driver-sync` driver library.

**Comment by velias** [comment]
Works like a charm, thanks a lot @OzWolf
